### ISSUE TITLE
next-i18next

### ISSUE THREAD

**Issue by datainvestor** [locize/locize#164]
I am trying to use in-context editor with my Next.js app using next-i18next but Im getting the following error when I paste and run the url in the Locize platfrom ( I run it on develpoment as localhost):

```
The InContext Editor failed to load properly.
This can have several reasons:

Wrong URL:

If your website wasn't loaded based on your given URL above there must be something wrong with it.

Is there a typo in the url?
Is your website not reachable?
Are you using the insecure http protocol on public domains instead of https?
Is your backend sending secure X-Frame headers? - You may try: [this chrome extension](https://chrome.google.com/webstore/detail/hiframe-the-hyper-iframe/joibipdfkleencgfgbbncoheaekffdfn)
Missing locize script:

In order to work properly the InContext Editor needs a script added to your site so it can exchange information (clicked text, saved changes,...). You need to add the [locize script](http://github.com/locize/locize) to your website.
```

How can I solve this? I think I need to import the Locize script somehow but in the documentation there is no mention of how to import it in the next-i18next next.js app.

**Comment by jamuhl** [comment]
https://github.com/locize/locize#with-a-bundler importing like any other module should be enough

**Comment by adrai** [comment]
https://github.com/locize/next-i18next-locize/blob/main/next-i18next.config.js#L27
