### ISSUE TITLE
Window "message" event listener causes an error when data is undefined.

### ISSUE THREAD

**Issue by mcchrish** [locize/locize#165]
## 🐛 Bug Report

This line causes an error when data is undefined.
https://github.com/locize/locize/blob/2de3be3b41b7c3602fd5b1e44585ae2f56427c04/src/PostMessageAPI.js#L95

## To Reproduce

A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

Should not cause an error. Should ignore messages that are not initiated by locize.

## Your Environment

- *runtime version*: node v16
- *module version*: >=2.3.0
- *os*: Linux
- *any other relevant information*

**Comment by jamuhl** [comment]
thank you for reporting...wasn't aware of apps running in other iframes using post message causing such errors (only way I could think of).

should be fixed in locize@2.4.5

**Comment by mcchrish** [comment]
Thank you for the quick response!
This works for me.
