### ISSUE TITLE
addLocizeSavedHandler doesnt get called

### ISSUE THREAD

**Issue by gust42** [locize/locize#172]
addLocizeSavedHandler doesnt do anything when used with react-intl and startStandalone

it gets added to the api object in postMessage.js but is never called as far as i can see
```
export function addLocizeSavedHandler (handler) {
  api.locizeSavedHandler = handler
}
```

im doing a workaround right now
```
    const onMessage = (m: MessageEvent<ILocizeMessage>) => {
      if (m.origin === 'https://www.locize.app') {
        console.log('message', m);
        if (m.data.message === 'committed') {
          console.log('message received', m);
          translations[locale.localeCode][m.data.payload.updated[0].key] =
            m.data.payload.updated[0].data.value;
        }
      }
    };
```

but would really like to use the correct way

**Comment by gust42** [comment]
Yeah exactly. using it in the iframe. That would be much appreciated.

Only problem I have left when this get fixed is that react-intl dont let me write the messagr IDs to dom, so I have to rely on the fuzzy search when selecting texts. I might be able to override their methods and print the ID in a parent element but that messes with the markup instead. Any tips there?

**Comment by jamuhl** [comment]
@gust42 would it be possible for you to use: https://github.com/i18next/i18next-subliminal/tree/main?tab=readme-ov-file#standalone-usage

```js
const wrapped = wrap('my text', { key: 'my.key', ns: 'my-ns', lng: 'en', source: 'translation' })
```

This adds meta information like key, namespace (locize files) as hidden chars to your translations (only use it in non production) -> if that would be possible we would be able to extend our side to read those (like in the solution that shows locize inside the iframe - instead of your app) and pass that info to locize.

**Comment by jamuhl** [comment]
addLocizeSavedHandler should be called in locize@3.2.4

**Comment by gust42** [comment]
That looks really good. Will check it out as soon as I get into the office. I should be able to wrap it. But if I understand correctly you need to make some changes as well to parse it?

**Comment by jamuhl** [comment]
yes...we will have to do some changes too. Those were planned later anyway - so no issue to fast forward that in our backlog...

it's more a questions if it's possible when using react-intl in general as I never used react-intl myself...

**Comment by gust42** [comment]
That would be awesone, im wrapping it like this and as far as i can tell it works but im not really sure how i can verify that the characters really are there

```
function LocizeFormatedMessage(props: ILocizeExtensionProps) {
  const { locale, translations, options } = useContext(LocizeContext);
  const {id} = props;
  
  const currentValue = translations[locale.localeCode]?.[id];

  updateLocize(currentValue, locale, props, options);

  const message = wrap(currentValue, {
    key: id,
    ns: options.namespace,
    lng: locale.localeCode,
  });

  // Return original FormattedMessage component
  return <FM {...props} defaultMessage={message} />;
}
```

there seam to be some issue with the 3.2.4 release, i can see the new changes in the src folder in node_module but they are not in the dist folder or locize.js file

**Comment by jamuhl** [comment]
i18next-subliminal support was added in locize@3.3.0 - ns, key info hidden with subliminal will be passed to locize...

**Comment by gust42** [comment]
It works like a charm. Well done!

Our translator is going to be so happy :D

I just have 2 UX notes for the editor:

When selecting a text in the iframe there is a huge content layout shift when the top box with the translation renders. Its pretty jarring size you have to close the box for the next text

Would it be possible to get show all languages for a text like in the other editor
![image](https://github.com/locize/locize/assets/1333999/96f6a889-4328-462f-b0ee-4397968764a4)


Really happy we picked locize!

**Comment by jamuhl** [comment]
@gust42 the incontext implementation relies on the components used in the "focus"-view, therefore it is not possible to easily show all other languages for editing -> but you can open the right sidebar which has the values of all languages in the last tab:

![image](https://github.com/locize/locize/assets/977772/76a110d9-3a2e-49ec-aeb8-548eeb0332c8)

For sure we will revisit the incontext view in future (still no perfect idea to get customers website and the editing part arranged without using to much screenspace)...there are plans to bring that up to the new standard that was introduced with the version shown here (currently only works with i18next - as we could add the subliminal plugin there without devs having todo the heavy lifting):

https://youtu.be/g3TmRfK9I2o?si=aB0a8POEzyn7LOvb&t=129

If you would prefer the new option - we could check how that could work without i18next?

**Comment by gust42** [comment]
Hey sorry for late response!

Thank you for all the help but i dont have anymore time to work on this :)

Will close this now. Everything works great in edtior!
